export const meanings = [
  { korean: '아이', english: 'child' },
  { korean: '이', english: 'two' },
  { korean: '오', english: 'five' },
  { korean: '오이', english: 'cucumber' },
  { korean: '우유', english: 'milk' },
  { korean: '가구', english: 'furniture' },
  { korean: '고기', english: 'meat' },
  { korean: '구', english: 'nine' },
  { korean: '구두', english: 'shoes' },
  { korean: '가다', english: 'to go' },
  { korean: '오다', english: 'to come' },
  { korean: '나', english: 'I' },
  { korean: '너', english: 'you' },
  { korean: '누나', english: 'older sister (used by a male)' },
  { korean: '라디오', english: 'radio' },
  { korean: '다리', english: 'leg' },
  { korean: '나라', english: 'country' },
  { korean: '드라마', english: 'drama' },
  { korean: '거미', english: 'spider' },
  { korean: '우리', english: 'we / our' },

  { korean: '가수', english: 'singer' },
  { korean: '비', english: 'rain' },
  { korean: '바보', english: 'fool' },
  { korean: '보다', english: 'to see' },
  { korean: '사다', english: 'to buy' },
  { korean: '소', english: 'cow' },
  { korean: '소고기', english: 'beef' },
  { korean: '버스', english: 'bus' },
  { korean: '아버지', english: 'father' },
  { korean: '어머니', english: 'mother' },
  { korean: '차', english: 'car / tea' },
  { korean: '코', english: 'nose' },
  { korean: '키', english: 'height' },
  { korean: '크다', english: 'to be big' },
  { korean: '타다', english: 'to ride' },
  { korean: '바지', english: 'pants' },
  { korean: '토마토', english: 'tomato' },
  { korean: '포도', english: 'grape' },
  { korean: '하다', english: 'to do' },
  { korean: '휴지', english: 'tissue' }
];

