export const meanings = [
  { korean: '아이', english: 'child' },
  { korean: '이', english: 'two' },
  { korean: '오', english: 'five' },
  { korean: '오이', english: 'cucumber' },
  { korean: '우유', english: 'milk' },
  { korean: '가구', english: 'furniture' },
  { korean: '고기', english: 'meat' },
  { korean: '구', english: 'nine' },
  { korean: '구두', english: 'shoes' },
  { korean: '가다', english: 'to go' },
  { korean: '오다', english: 'to come' },
  { korean: '나', english: 'I' },
  { korean: '너', english: 'you' },
  { korean: '누나', english: 'older sister (used by a male)' },
  { korean: '라디오', english: 'radio' },
  { korean: '다리', english: 'leg' },
  { korean: '나라', english: 'country' },
  { korean: '드라마', english: 'drama' },
  { korean: '거미', english: 'spider' },
  { korean: '우리', english: 'we / our' },

  { korean: '가수', english: 'singer' },
  { korean: '비', english: 'rain' },
  { korean: '바보', english: 'fool' },
  { korean: '보다', english: 'to see' },
  { korean: '사다', english: 'to buy' },
  { korean: '소', english: 'cow' },
  { korean: '소고기', english: 'beef' },
  { korean: '버스', english: 'bus' },
  { korean: '아버지', english: 'father' },
  { korean: '어머니', english: 'mother' },
  { korean: '차', english: 'car / tea' },
  { korean: '코', english: 'nose' },
  { korean: '키', english: 'height' },
  { korean: '크다', english: 'to be big' },
  { korean: '타다', english: 'to ride' },
  { korean: '바지', english: 'pants' },
  { korean: '토마토', english: 'tomato' },
  { korean: '포도', english: 'grape' },
  { korean: '하다', english: 'to do' },
  { korean: '휴지', english: 'tissue' },

  { korean: '끄다', english: 'to turn off' },
  { korean: '토끼', english: 'rabbit' },
  { korean: '오빠', english: 'older brother (used by a female)' },
  { korean: '바쁘다', english: 'to be busy' },
  { korean: '아저씨', english: 'middle-aged man / mister' },
  { korean: '쓰다', english: 'to write / to wear / to use / to be bitter' },
  { korean: '싸다', english: 'to be cheap / to pack' },
  { korean: '비싸다', english: 'to be expensive' },
  { korean: '짜다', english: 'to be salty' },
  { korean: '찌다', english: 'to steam / to gain weight' },

  { korean: '위', english: 'on / above' },
  { korean: '왜', english: 'why' },
  { korean: '아래', english: 'under / below' },
  { korean: '개', english: 'dog' },
  { korean: '게', english: 'crab' },
  { korean: '가게', english: 'shop / store' },
  { korean: '귀', english: 'ear' },
  { korean: '과자', english: 'snack' },
  { korean: '사과', english: 'apple / apology' },
  { korean: '웨이터', english: 'waiter' },
  { korean: '돼지', english: 'pig' },
  { korean: '노래', english: 'song' },
  { korean: '배', english: 'pear / belly / boat' },
  { korean: '베개', english: 'pillow' },
  { korean: '새', english: 'bird' },
  { korean: '새우', english: 'shrimp' },
  { korean: '회사', english: 'company / office' },
  { korean: '케이크', english: 'cake' },
  { korean: '시계', english: 'clock / watch' },

  { korean: '수박', english: 'watermelon' },
  { korean: '밖', english: 'outside' },
  { korean: '부엌', english: 'kitchen' },
  { korean: '안', english: 'inside / not' },
  { korean: '눈', english: 'eye / snow' },
  { korean: '한국', english: 'Korea' },
  { korean: '친구', english: 'friend' },
  { korean: '미얀마', english: 'Myanmar' },
  { korean: '언니', english: 'older sister (used by a female)' },
  { korean: '달', english: 'moon / month' },
  { korean: '물', english: 'water' },
  { korean: '한글', english: 'Hangeul (Korean script)' },
  { korean: '미얀마글', english: 'Burmese script' },
  { korean: '닫다', english: 'to close' },
  { korean: '꽃', english: 'flower' },
  { korean: '밭', english: 'field' },
  { korean: '옷', english: 'clothes' },
  { korean: '있다', english: 'to have / to exist' },
  { korean: '낮', english: 'daytime' },
  { korean: '밤', english: 'night / chestnut' },
  { korean: '힘', english: 'strength / power' },
  { korean: '엄마', english: 'mom' },
  { korean: '입', english: 'mouth' },
  { korean: '집', english: 'house / home' },
  { korean: '앞', english: 'front' },
  { korean: '뒤', english: 'back / behind' },
  { korean: '옆', english: 'side / beside' },
  { korean: '강', english: 'river' },
  { korean: '한강', english: 'Han River' },
  { korean: '방', english: 'room' },
  { korean: '공', english: 'ball / zero (digits)' },
  { korean: '영', english: 'zero (math/temp)' },
  { korean: '빵', english: 'bread' }
];

